FROM golang:1.22-alpine AS builder

WORKDIR /app

# 1️⃣ cache de dependências
COPY go.mod go.sum ./
RUN go mod download

# 2️⃣ copia código
COPY . .

# 3️⃣ build otimizado
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api

# 4️⃣ imagem final leve
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/api .
RUN chmod +x ./api

EXPOSE 8080

CMD ["./api"]