version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pix
      POSTGRES_PASSWORD: pix
      POSTGRES_DB: pix
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://pix:pix@postgres:5432/pix?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrate
      - redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    depends_on:
      - postgres
      - migrate
      - redis